namespace OpenUtau.Colors;

/// <summary>
/// Built-in theme snapshots. Values must stay in sync with DarkTheme.axaml / LightTheme.axaml.
/// ResourceInclude dictionaries are not enumerable reliably at theme-creation time.
/// </summary>
public static class BuiltInThemeLoader {
    public static ThemeYaml CreateFromBuiltIn(string baseTheme, string name) {
        var yaml = baseTheme == "Dark" ? CreateDark() : CreateLight();
        yaml.Name = name;
        return yaml;
    }

    public static ThemeYaml CreateDark() {
        return new ThemeYaml {
            IsDarkMode = true,
            BackgroundColor = "#212121",
            BackgroundColorPointerOver = "#2F2F2F",
            TransportToolbarOffHoverColor = "#3A3A3A",
            BackgroundColorPressed = "#2F2F2F",
            BackgroundColorDisabled = "#212121",
            ForegroundColor = "#F0F0F0",
            ForegroundColorPointerOver = "#FCFCFC",
            ForegroundColorPressed = "#FCFCFC",
            ForegroundColorDisabled = "#A6A6A6",
            BorderColor = "#E0E0E0",
            BorderColorPointerOver = "#FCFCFC",
            SystemAccentColor = "#7271C9",
            SystemAccentColorLight1 = "#E0E0E0",
            SystemAccentColorDark1 = "#B6B6B6",
            NeutralAccentColor = "#FCFCFC",
            NeutralAccentColorPointerOver = "#FCFCFC",
            AccentColor1 = "#E0E0E0",
            AccentColor1Note = "#4C4C7A",
            AccentColor2 = "#7271C9",
            AccentColor3 = "#FCFCFC",
            NoteBorderColor = "#7B79D9",
            NoteBorderColorPressed = "#ADACFC",
            TickLineColor = "#060606",
            BarNumberColor = "#E0E0E0",
            FinalPitchColor = "#CAFFFFFF",
            TrackBackgroundAltColor = "#2B2B2B",
            WarningColor = "#433519",
            ToolbarCheckedHoverColor = "#D8D8D8",
            ToolTipForegroundColor = "#FFFFFF",
            WorkspaceCanvasColor = "#121212",
            WorkspaceCardColor = "#212121",
            WorkspaceElevatedSurfaceColor = "#2B2B2B",
            MutedIconColor = "#808080",
            PianoRollWaveformPeakColor = "#59B5B5B5",
            PianoRollToolbarStripColor = "#202020",
            PianoRollToolbarButtonHoverColor = "#313131",
            PianoRollTimelineStripColor = "#1B1B1B",
            AppTopBarTransportStripColor = "#323232",
            AppTopBarTransportHoverColor = "#454545",
            AppTopBarValueStripColor = "#1C1C1C",
            AppTopBarValueDividerColor = "#3A3A3A",
            WhiteKeyColorLeft = "#C0C0C0",
            WhiteKeyColorRight = "#E0E0E0",
            ToolbarCheckedPianoLightColor = "#F0F0F0",
            WhiteKeyNameColor = "#212121",
            CenterKeyColorLeft = "#A9A6CD",
            CenterKeyColorRight = "#D3CFFF",
            CenterKeyNameColor = "#4433FF",
            BlackKeyColorLeft = "Transparent",
            BlackKeyColorRight = "Transparent",
            BlackKeyNameColor = "#FCFCFC",
        };
    }

    public static ThemeYaml CreateLight() {
        return new ThemeYaml {
            IsDarkMode = false,
            BackgroundColor = "#FCFCFC",
            BackgroundColorPointerOver = "#F0F0F0",
            TransportToolbarOffHoverColor = "#F6F6F6",
            BackgroundColorPressed = "#E0E0E0",
            BackgroundColorDisabled = "#D0D0D0",
            ForegroundColor = "#111111",
            ForegroundColorPointerOver = "#111111",
            ForegroundColorPressed = "#202020",
            ForegroundColorDisabled = "#808080",
            BorderColor = "#707070",
            BorderColorPointerOver = "#B0B0B0",
            SystemAccentColor = "#4F4F6E",
            SystemAccentColorLight1 = "#393957",
            SystemAccentColorDark1 = "#2B2B46",
            NeutralAccentColor = "#A1A1B3",
            NeutralAccentColorPointerOver = "#8A8A9A",
            AccentColor1 = "#A9A6CD",
            AccentColor1Note = "#A9A6CD",
            AccentColor2 = "#635EA6",
            AccentColor3 = "#736DC1",
            NoteBorderColor = "#7B79D9",
            NoteBorderColorPressed = "#4C4B98",
            TickLineColor = "#C0C0CA",
            BarNumberColor = "#4F4F6E",
            FinalPitchColor = "#FF8979FF",
            TrackBackgroundAltColor = "#F0F0F0",
            WarningColor = "#FFF4CE",
            ToolbarCheckedHoverColor = "#E0E0E0",
            ToolTipForegroundColor = "#FFFFFF",
            WorkspaceCanvasColor = "#E4E4E8",
            WorkspaceCardColor = "#FCFCFC",
            WorkspaceElevatedSurfaceColor = "#E8E8EC",
            MutedIconColor = "#808080",
            PianoRollWaveformPeakColor = "#59999999",
            PianoRollToolbarStripColor = "#202020",
            PianoRollToolbarButtonHoverColor = "#313131",
            PianoRollTimelineStripColor = "#D8D8DE",
            AppTopBarTransportStripColor = "#E8E8EC",
            AppTopBarTransportHoverColor = "#F4F4F8",
            AppTopBarValueStripColor = "#D8D8DE",
            AppTopBarValueDividerColor = "#C0C0C8",
            WhiteKeyColorLeft = "#FCFCFC",
            WhiteKeyColorRight = "#FCFCFC",
            ToolbarCheckedPianoLightColor = "#FCFCFC",
            WhiteKeyNameColor = "#343434",
            CenterKeyColorLeft = "#A9A6CD",
            CenterKeyColorRight = "#D3CFFF",
            CenterKeyNameColor = "#111111",
            BlackKeyColorLeft = "#45445C",
            BlackKeyColorRight = "#45445C",
            BlackKeyNameColor = "#FCFCFC",
        };
    }
}
