on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        default: '0.0.0.0'
        required: true
        type: string
      create-release:
        type: boolean
        description: "Create Release"

jobs:
  release:
    runs-on: ${{ matrix.os.runs-on }}

    strategy:
      matrix:
        os:
          - runs-on: windows-latest
            name: win-x64
            arch: x64
            os: win
          - runs-on: macos-latest
            name: osx-x64
            arch: x64
            os: osx
          - runs-on: ubuntu-latest
            name: linux-x64
            arch: x64
            os: linux
          - runs-on: windows-latest
            name: win-arm64
            arch: arm64
            os: win
          - runs-on: macos-latest
            name: osx-arm64
            arch: arm64
            os: osx
          - runs-on: ubuntu-latest
            name: linux-arm64
            arch: arm64
            os: linux

    steps:
    - uses: actions/checkout@v1

    - name: Patch Versions
      uses: justalemon/VersionPatcher@v0.8
      with:
        version: ${{ inputs.version }}
        csproj-files: "OpenUtau/*.csproj"

    - name: restore
      run: dotnet restore OpenUtau -r ${{ matrix.os.name }}

    - name: build
      run: dotnet publish OpenUtau -c Release -r ${{ matrix.os.name }} --self-contained true -o bin/${{ matrix.os.name }}

    - name: add openutau.plugins.builtin
      shell: pwsh
      run: copy OpenUtau.Plugin.Builtin\bin\Release\netstandard2.1\OpenUtau.Plugin.Builtin.dll -Destination bin\${{ matrix.os.name }}

    - name: DirectML
      if: ${{ matrix.os.runs-on == 'windows-latest' }}
      run: |
        curl -L https://www.nuget.org/api/v2/package/Microsoft.AI.DirectML/1.12.0 -o Microsoft.AI.DirectML.nupkg
        mkdir Microsoft.AI.DirectML
        tar -xf Microsoft.AI.DirectML.nupkg -C Microsoft.AI.DirectML
        xcopy /Y Microsoft.AI.DirectML\bin\${{ matrix.os.arch }}-${{ matrix.os.os }}\DirectML.dll bin\${{ matrix.os.name }}\

    - name: compress
      run: 7z a ou-lunai-${{ matrix.os.name }}.zip ./bin/${{ matrix.os.name }}/*

    - name: download vocoder
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: https://github.com/openvpi/vocoders/releases/download/nsf-hifigan-44.1k-hop512-128bin-2024.02/nsf_hifigan_44.1k_hop512_128bin_2024.02_logE.oudep
        file-name: nsf_hifigan_44.1k_hop512_128bin_2024.02_logE.oudep
        location: ./

    - name: extract vocoder
      run: 7z x -o"./bin/${{ matrix.os.name }}/Dependencies/nsf_hifigan" ./nsf_hifigan_44.1k_hop512_128bin_2024.02_logE.oudep

    - name: compress vocoder
      if: ${{ matrix.os.runs-on == 'windows-latest' }} or ${{ matrix.os.runs-on == 'macos-latest' }} or ${{ matrix.os.runs-on == 'ubuntu-latest' }}
      run: 7z a ou-lunai-${{ matrix.os.name }}.zip ./bin/${{ matrix.os.name }}/*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ou-lunai-${{ matrix.os.name }}.zip
        path: ou-lunai-${{ matrix.os.name }}.zip

    - name: Create release and upload artifact
      if: ${{ inputs.create-release }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.version }}
        files: |
          ou-lunai-${{ matrix.os.name }}.zip
